project_id = "fdpmktqguwgvnioxpbbm"

[functions.realtime-session]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.lti-launch]
verify_jwt = false

[functions.agent-evaluation]
verify_jwt = false

[functions.evaluate-session]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false